# Generated by Django 5.0.14 on 2025-09-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Living'), ('books', 'Books'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
