"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOCAL_ENV_FILE = BASE_DIR / '.env'
if LOCAL_ENV_FILE.exists():
    for raw_line in LOCAL_ENV_FILE.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nwqdlwuj$imalc$8y4a7d##$+3t#2$%-xi4s(+_=nzp@$gfv(d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'users',
    'products',
    'stores',
    'transactions',
    'export_guides',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

MSSQL_DATABASES = {
    'default': {
        'ENGINE': 'mssql',  # mssql-django package
        'NAME': 'tradelistic_db',
        'HOST': 'DESKTOP-4J27RLH\\SQLEXPRESS',
        'USER': 'test',
        'PASSWORD': 'test',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'TrustServerCertificate': 'yes',
            'MARS_Connection': True,
            'unicode_results': True,
        },
    }
}

# SQLite configuration (backup for testing only)
SQLITE_DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

try:
    import pyodbc  # noqa: F401
    PYODBC_AVAILABLE = True
except Exception:
    PYODBC_AVAILABLE = False

SQLSERVER_DRIVER = os.environ.get('SQLSERVER_DRIVER', 'ODBC Driver 17 for SQL Server')
if PYODBC_AVAILABLE:
    try:
        available_sql_drivers = pyodbc.drivers()
        if SQLSERVER_DRIVER not in available_sql_drivers and 'SQL Server' in available_sql_drivers:
            SQLSERVER_DRIVER = 'SQL Server'
    except Exception:
        pass

MSSQL_DATABASES['default']['OPTIONS']['driver'] = SQLSERVER_DRIVER
if SQLSERVER_DRIVER == 'SQL Server':
    MSSQL_DATABASES['default']['OPTIONS']['host_is_server'] = True

USE_SQLITE = os.environ.get('USE_SQLITE', '').lower() in {'1', 'true', 'yes'}
DATABASES = SQLITE_DATABASES if USE_SQLITE or not PYODBC_AVAILABLE else MSSQL_DATABASES


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3002",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3002",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# OpenAI-compatible vision API config.
# Set these in PowerShell before starting backend:
# $env:LLAMA_API_KEY="your_key"
# $env:LLAMA_API_URL="https://integrate.api.nvidia.com/v1/chat/completions"
# $env:LLAMA_MODEL="meta/llama-4-maverick-17b-128e-instruct"
LLAMA_API_KEY = os.environ.get('LLAMA_API_KEY', '')
LLAMA_API_URL = os.environ.get('LLAMA_API_URL', 'https://integrate.api.nvidia.com/v1/chat/completions')
LLAMA_MODEL = os.environ.get('LLAMA_MODEL', 'meta/llama-4-maverick-17b-128e-instruct')

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# JWT settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# User model
AUTH_USER_MODEL = 'users.User'
