# Generated by Django 5.0.14 on 2025-09-20 16:17

from django.db import migrations, connection


def cleanup_duplicate_tables(apps, schema_editor):
    """Remove duplicate tables and ensure proper relationships"""
    db_alias = schema_editor.connection.alias
    with connection.cursor() as cursor:
        try:
            # Check if duplicate tables exist and drop them
            cursor.execute("""
                IF OBJECT_ID('sales_sale', 'U') IS NOT NULL
                    DROP TABLE sales_sale
            """)
            print("Dropped sales_sale table if it existed")
        except Exception as e:
            print(f"Error dropping sales_sale: {e}")
            
        try:
            cursor.execute("""
                IF OBJECT_ID('reviews_review', 'U') IS NOT NULL
                    DROP TABLE reviews_review
            """)
            print("Dropped reviews_review table if it existed")
        except Exception as e:
            print(f"Error dropping reviews_review: {e}")
            
        try:
            cursor.execute("""
                IF OBJECT_ID('reviews_reviewhelpfulness', 'U') IS NOT NULL
                    DROP TABLE reviews_reviewhelpfulness
            """)
            print("Dropped reviews_reviewhelpfulness table if it existed")
        except Exception as e:
            print(f"Error dropping reviews_reviewhelpfulness: {e}")
            
        try:
            cursor.execute("""
                IF OBJECT_ID('reviews_reviewresponse', 'U') IS NOT NULL
                    DROP TABLE reviews_reviewresponse
            """)
            print("Dropped reviews_reviewresponse table if it existed")
        except Exception as e:
            print(f"Error dropping reviews_reviewresponse: {e}")


def ensure_proper_foreign_keys(apps, schema_editor):
    """Ensure foreign key relationships are properly set up"""
    db_alias = schema_editor.connection.alias
    with connection.cursor() as cursor:
        try:
            # Check if foreign key constraint exists for review.sale_id
            cursor.execute("""
                SELECT CONSTRAINT_NAME 
                FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
                WHERE CONSTRAINT_NAME LIKE '%transactions_review%sale%'
            """)
            
            result = cursor.fetchone()
            if not result:
                print("Foreign key constraint for review.sale_id might need attention")
            else:
                print("Foreign key constraint exists for review.sale_id")
                
        except Exception as e:
            print(f"Error checking foreign key constraints: {e}")


def reverse_cleanup(apps, schema_editor):
    """This migration is not reversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_tables, reverse_cleanup),
        migrations.RunPython(ensure_proper_foreign_keys, reverse_cleanup),
    ]
