# Generated by Django 5.0.14 on 2025-09-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_fix_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
