# Generated by Django 5.0.14 on 2025-09-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_add_sales_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sales_id',
            field=models.CharField(blank=True, help_text='Sales ID from transactions_sale table', max_length=50, null=True),
        ),
    ]
