# Generated by Django 5.0.14 on 2025-12-10 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_add_sales_id_to_review'),
        ('products', '0010_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviews',
                to='products.product'
            ),
        ),
    ]
