# Generated by Django 5.0.14 on 2025-09-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_type_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
