# Generated by Django 5.0.14 on 2025-12-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('importer', 'Importer'), ('exporter', 'Exporter')], help_text='User type for regular users. Admin users do not need a type.', max_length=10, null=True),
        ),
    ]
